# src/perguntas.py
# Estrutura das 70 perguntas e pesos para o diagnóstico ICE³-R + DREXUS

perguntas = {
    "If – Integridade Funcional": [
        ("A missão crítica da unidade está claramente definida e operacionalizada?", 0.15),
        ("Os processos essenciais operam sob contingência mínima com autonomia funcional?", 0.10),
        ("A cadeia de decisão se mantém funcional durante eventos extremos?", 0.15),
        ("As equipes conhecem e priorizam a missão crítica sob pressão?", 0.10),
        ("Há redundância mínima viável para manter a integridade operacional?", 0.10),
        ("Os sistemas de controle de qualidade funcionam mesmo em contextos adversos?", 0.10),
        ("A liderança consegue reorganizar recursos rapidamente sem comprometer a missão?", 0.10),
        ("Existe teste periódico da resiliência dos processos críticos?", 0.05),
        ("Há indicadores de missão crítica com resposta em tempo real?", 0.10),
        ("A integridade dos processos é percebida e valorizada pela cultura da organização?", 0.05),
    ],
    "Cm – Capacidade de Modularidade": [
        ("A organização é composta por módulos autônomos?", 0.10),
        ("Os módulos podem operar independentemente se necessário?", 0.10),
        ("Existe flexibilidade para reorganização estrutural?", 0.10),
        ("Os módulos compartilham recursos de maneira eficiente?", 0.10),
        ("Há protocolos claros de comunicação entre módulos?", 0.10),
        ("Os módulos conseguem absorver choques sem impactar o todo?", 0.10),
        ("A modularidade é revisada periodicamente?", 0.10),
        ("Existem métricas de performance por módulo?", 0.10),
        ("Os módulos têm autonomia de decisão em situações críticas?", 0.10),
        ("A modularidade é percebida como valor estratégico?", 0.10),
    ],
    "Et – Evolução sob Estresse": [
        ("A organização aprende com eventos inesperados?", 0.10),
        ("Há processos para capturar aprendizados de crises?", 0.10),
        ("Mudanças são implementadas rapidamente após eventos críticos?", 0.10),
        ("A cultura valoriza adaptação contínua?", 0.10),
        ("As equipes são treinadas para evolução contínua?", 0.10),
        ("Existe monitoramento dos aprendizados implementados?", 0.10),
        ("A evolução é mensurada por indicadores específicos?", 0.10),
        ("Os aprendizados são compartilhados entre equipes?", 0.10),
        ("Feedbacks de evolução são sistemáticos?", 0.10),
        ("A evolução é percebida como diferencial competitivo?", 0.10),
    ],
    "DREq – Densidade de DREs": [
        ("A organização tem histórico de decisões regenerativas?", 0.10),
        ("As DREs são documentadas sistematicamente?", 0.10),
        ("Há indicadores de densidade de DREs?", 0.10),
        ("As DREs são debatidas em fóruns internos?", 0.10),
        ("A cultura incentiva decisões regenerativas?", 0.10),
        ("Existem líderes referência em DREs?", 0.10),
        ("As DREs são reconhecidas e celebradas?", 0.10),
        ("A densidade de DREs aumenta ao longo do tempo?", 0.10),
        ("As DREs impactam processos-chave?", 0.10),
        ("A densidade de DREs é percebida como estratégica?", 0.10),
    ],
    "Lc – Lógica Contextual": [
        ("A organização identifica corretamente seu contexto de atuação?", 0.10),
        ("As decisões consideram variáveis contextuais?", 0.10),
        ("Há análise contínua de contexto?", 0.10),
        ("Mudanças contextuais são rapidamente percebidas?", 0.10),
        ("A lógica de decisão é adaptada ao contexto?", 0.10),
        ("Existem ferramentas para análise de contexto?", 0.10),
        ("A contextualização é debatida em reuniões?", 0.10),
        ("A lógica contextual é revisada periodicamente?", 0.10),
        ("As equipes compreendem o contexto em que atuam?", 0.10),
        ("A lógica contextual é vista como diferencial?", 0.10),
    ],
    "Im – Impacto Sistêmico das DREs": [
        ("As DREs geram impacto além da organização?", 0.10),
        ("O impacto é monitorado sistematicamente?", 0.10),
        ("Há indicadores de impacto sistêmico?", 0.10),
        ("As partes interessadas percebem o impacto das DREs?", 0.10),
        ("O impacto influencia decisões futuras?", 0.10),
        ("O impacto sistêmico é debatido em fóruns internos?", 0.10),
        ("Existem parcerias para ampliar o impacto?", 0.10),
        ("O impacto sistêmico é comunicado externamente?", 0.10),
        ("O impacto é revisado periodicamente?", 0.10),
        ("O impacto sistêmico é visto como valor?", 0.10),
    ],
    "Pv – Propósito Vivo": [
        ("A organização tem um propósito claro e vivo?", 0.10),
        ("O propósito é comunicado a todos?", 0.10),
        ("O propósito é revisado periodicamente?", 0.10),
        ("As decisões refletem o propósito?", 0.10),
        ("O propósito é debatido em todos os níveis?", 0.10),
        ("O propósito orienta a estratégia?", 0.10),
        ("O propósito é percebido externamente?", 0.10),
        ("O propósito é celebrado em conquistas?", 0.10),
        ("O propósito é adaptado quando necessário?", 0.10),
        ("O propósito vivo é reconhecido como diferencial?", 0.10),
    ],
}

variaveis_siglas = {
    "If – Integridade Funcional": "If",
    "Cm – Capacidade de Modularidade": "Cm",
    "Et – Evolução sob Estresse": "Et",
    "DREq – Densidade de DREs": "DREq",
    "Lc – Lógica Contextual": "Lc",
    "Im – Impacto Sistêmico das DREs": "Im",
    "Pv – Propósito Vivo": "Pv",
}